export default [
	// 'stackable/accordion',
	// 'stackable/blockquote',
	// 'stackable/button-group',
	// 'stackable/button',
	// 'stackable/call-to-action',
	// 'stackable/card',
	// 'stackable/columns',
	// 'stackable/count-up',
	// 'stackable/divider',
	// 'stackable/expand',
	// 'stackable/feature',
	// 'stackable/feature-grid',
	// 'stackable/hero',
	// 'stackable/heading',
	// 'stackable/icon-box',
	'stackable/icon-button',
	'stackable/icon',
	'stackable/icon-label',
	'stackable/icon-list',
	'stackable/image',
	'stackable/image-box',
	'stackable/notification',
	'stackable/number-box',
	'stackable/posts',
	'stackable/price',
	'stackable/pricing-box',
	'stackable/separator',
	'stackable/spacer',
	'stackable/subtitle',
	'stackable/team-member',
	'stackable/testimonial',
	'stackable/text',
	'stackable/video-popup',
]
