export default [
	'stackable/accordion',
	'stackable/blockquote',
	'stackable/button-group',
	'stackable/button',
	'stackable/icon-button', // button-group parent block
	'stackable/call-to-action',
	'stackable/card',
	'stackable/columns',
	'stackable/container',
	'stackable/count-up',
	'stackable/expand',
	'stackable/feature',
	'stackable/feature-grid',
	'stackable/hero',
	'stackable/heading',
	'stackable/icon-box',
	'stackable/icon',
	'stackable/icon-label',
	'stackable/icon-list',
	'stackable/image',
	'stackable/notification',
	'stackable/number-box',
	'stackable/price',
	'stackable/pricing-box',
	'stackable/subtitle',
	'stackable/testimonial',
	'stackable/text',
	'stackable/video-popup',
	// TODO: More blocks to be added
]
