name: e2e-test-wp56
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  skip-workflow:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.skip-workflow.outputs.skip }}

    steps:
      - uses: actions/checkout@v2

      - name: Skip Workflow
        id: skip-workflow
        uses: saulmaldonado/skip-workflow@v1
        with:
          phrase: '[skip wp-56]'
          github-token: ${{ github.token }}
  test:
    needs: skip-workflow
    if: ${{ !needs.skip-workflow.outputs.skip }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
        total-machines: [20]

    steps:
    - uses: actions/checkout@v2

    - name: Cache node modules
      if: ${{ !steps.skip-workflow.outputs.skip }}
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Setup the Stackable Free and Premium Repository
      if: ${{ !steps.skip-workflow.outputs.skip }}
      run: |
        git clone https://github.com/gambitph/Stackable.git
        cd Stackable
        git clone https://${{ secrets.ACCESS_KEY }}@github.com/bfintal/Stackable-Premium pro__premium_only
        cd ..

    - name: Setup Node
      if: ${{ !steps.skip-workflow.outputs.skip }}
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install @wordpress/env
      if: ${{ !steps.skip-workflow.outputs.skip }}
      run: npm install -g @wordpress/env

    - name: Build Stackable Premium
      if: ${{ !steps.skip-workflow.outputs.skip }}
      run: |
        cd Stackable
        npm ci
        cd pro__premium_only
        npm ci
        npm run build --if-present

    # Install all dependencies from composer.json
    - name: Install WordPress Version
      if: ${{ !steps.skip-workflow.outputs.skip }}
      run: |
        composer require roots/wordpress:5.6.3 --dev

    - name: Run WordPress Environment
      if: ${{ !steps.skip-workflow.outputs.skip }}
      run: wp-env start

    - name: Run Test Suite
      if: ${{ !steps.skip-workflow.outputs.skip }}
      uses: cypress-io/github-action@v2
      with:
        command: npm run cy:run:parallel -- --machine-number=${{ matrix.containers }} --total-machines=${{ matrix.total-machines }} --spec=cypress/integration/**/*.spec.js --browser=chrome --env=STACKABLE_PREMIUM_CODE=${{ secrets.STACKABLE_PREMIUM_CODE }},GITHUB_ACTIONS=1 --config=baseUrl=http://localhost:8889

    - name: Upload E2E Test Results
      if: ${{ !steps.skip-workflow.outputs.skip }}
      uses: actions/upload-artifact@v2
      with:
        name: e2e-test-results-${{ matrix.containers }}
        path: cypress/results/e2e-test-results.xml

  publish-test-results:
    name: Publish E2E Test Results
    needs: test
    runs-on: ubuntu-latest
    if: ${{ !needs.skip-workflow.outputs.skip }}

    steps:
    - name: Download Artifacts
      if: ${{ !steps.skip-workflow.outputs.skip }}
      uses: actions/download-artifact@v2
      with:
        path: artifacts

    - name: Publish E2E Test Results
      if: ${{ !steps.skip-workflow.outputs.skip }}
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        files: artifacts/**/*.xml
        check_name: E2E Test Results
